config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    namespace :admin do
      root 'bulletins#moderate'

      resources :categories, only: %i[index new create edit update destroy]

      resources :bulletins, only: %i[index show] do
        collection do
          get 'moderate'
        end
        member do
          patch 'publish'
          patch 'reject'
          patch 'archive'
        end
      end
    end

    resources :bulletins, only: %i[index new create show edit update] do
      member do
        patch 'send_for_moderation'
        patch 'archive'
      end
    end

    resource :profile, only: :show

    root 'bulletins#index'

    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    delete 'auth/sign_out', as: :sign_out
  end
end

app/views/layouts/shared/_admin_menu.html.slim
ul.nav.flex-column.nav-pills
  li.nav-item
    = menu_item_link t('.on_moderation'), admin_root_path, class: 'nav-link link-dark'
  li.nav-item
    = menu_item_link t('.all_bulletins'), admin_bulletins_path, class: 'nav-link link-dark'
  li.nav-item
    = menu_item_link t('categories'), admin_categories_path, class: 'nav-link link-dark'

app/views/layouts/shared/_alerts.html.slim
- if flash.any?
  .container.my-2
    - flash.each do |message_type, msg|
      - case message_type.to_s
      - when 'alert'
        .alert.alert-danger
          = msg
      - when 'notice'
        .alert.alert-success
          = msg
      - else
        div class = "alert alert-#{message_type}"
          = msg

app/views/layouts/shared/_nav.html.slim
nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  .container
    = link_to t('.title'), root_path, class: 'navbar-brand'
    button.navbar-toggler(type="button"
      data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false"
      aria-label="Toggle navigation")
      span.navbar-toggler-icon
    .collapse.navbar-collapse#navbarSupportedContent
      ul.navbar-nav.ms-auto.mb-2.mb-lg-0
        li.nav-item
          = link_to t('.home'), root_path, class: 'nav-link'
        - if signed_in?
          li.nav-item
            = link_to t('.my_bulletins'), profile_path, class: 'nav-link'
          li.nav-item
            = link_to t('.add_bulletin'), new_bulletin_path, class: 'nav-link'
      ul.navbar-nav.ms-auto.mb-2.mb-lg-0
        - if admin?
          li.nav-item
            = link_to t('.admin_area'), admin_root_path, class: 'nav-link'
        - if signed_in?
          li.nav-item
            = link_to t('.sign_out'), sign_out_path, class: 'nav-link', method: :delete
        - else
          li.nav-item
            = link_to auth_request_path(:github), class: 'nav-link', method: :post do
              i.fa-brands.fa-github.me-2
              = t('.sign_in')