config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope module: :web do
    namespace :admin do
      root 'bulletins#moderate'

      resources :categories, only: %i[index new create edit update destroy]

      resources :bulletins, only: %i[index show] do
        collection do
          get 'moderate'
        end
        member do
          patch 'publish'
          patch 'reject'
          patch 'archive'
        end
      end
    end

    resources :bulletins, only: %i[index new create show edit update] do
      member do
        patch 'send_for_moderation'
        patch 'archive'
      end
    end

    resource :profile, only: :show

    root 'bulletins#index'

    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    delete 'auth/sign_out', as: :sign_out
  end
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :bulletins, dependent: :restrict_with_exception
  validates :name, presence: true, uniqueness: true
end

app/controllers/web/admin/categories_controller.rb
# frozen_string_literal: true

module Web::Admin
  class CategoriesController < ApplicationController
    def index
      @categories = Category.all.order(:name).page(params[:page])
      @resource_actions = %i[edit destroy]
    end

    def new
      @category = Category.new
    end

    def create
      @category = Category.new category_params
      if @category.save
        redirect_to admin_categories_path, success: t('.success')
      else
        flash[:warning] = t('.fail')
        render :new, status: :unprocessable_entity
      end
    end

    def edit
      @category = Category.find params[:id]
      authorize @category
    end

    def update
      @category = Category.find params[:id]
      authorize @category
      if @category.update category_params
        redirect_to admin_categories_path, success: t('.success')
      else
        flash[:warning] = t('.fail')
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @category = Category.find params[:id]
      authorize @category
      if @category.destroy
        flash[:success] = t('.success')
      else
        flash[:warning] = t('.fail')
      end
      redirect_to admin_categories_path
    end

    private

    def category_params
      params.require(:category).permit(:name)
    end
  end
end

app/views/web/admin/categories/_form.html.slim
= simple_form_for [:admin, category] do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  = f.input :name
  = f.submit class: 'btn btn-primary mt-2'

app/views/web/admin/categories/edit.html.slim
.p-4.align-items-center.border.shadow.bg-white.rounded-3
  .row
    .p-3.p-lg-5.pt-lg-0
      .mb-4
        h1.h2.mb-4
          = t('.edit_category')
        hr
        = render 'form', category: @category

app/views/web/admin/categories/index.html.slim
h1.h2.mb-4
  = t('.categories')
= link_to t('.add_category'), new_admin_category_path
.row.mt-2
  table.table.table-bordless
    tbody
      - @categories.each do |category|
        tr
          td
            = category.name
          td
            - @resource_actions.each do |action|
              = icon_action_link(action,
                url_for(action: action, id: category.id),
                enabled: allow?(action, category))

= paginate @categories, theme: 'bootstrap-5'

app/views/web/admin/categories/new.html.slim
.p-4.align-items-center.border.shadow.bg-white.rounded-3
  .row
    .p-3.p-lg-5.pt-lg-0
      .mb-4
        h1.h2.mb-4
          = t '.new_category'
        hr
        = render 'form', category: @category